import turtle
t = turtle.Turtle()
s= turtle.Screen()
s.bgcolor("black")
t.pensize(3)
t.pencolor("lightgreen")
s.title("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------")
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
turtle.done()